apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-vol2
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: http-secret
  containers:
    - name: test-containers
      image: alpine:latest
      command: ["sleep", "9999"]
      volumeMounts:
        - name: sectret-volume
          mountPath: /etc/sectret-volume
