apiVersion: v1
kind: Pod
metadata:
  name: secret-pod2
spec:
  containers:
  - name: sectret-container
    image: alpine:latest
    command: ["sleep", "9999"]
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: http-secret
            key: username
      - name: SECRET_PASSWORDS
        valueFrom:
          secretKeyRef:
            name: http-secret
            key: password
  restartPolicy: Never
