apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-lb
  labels:
    app: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  selector:
    app: nginx-ingress
---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-ingress-dc
  labels:
    app: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
        - image: nginxdemos/nginx-ingress:0.9.0
          name: nginx-ingress
          ports:
            - containerPort: 80
              name: http
